language: php

php:
  - hhvm
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install

script:
  - composer lint
  - composer sniff
  - composer phpunit-coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/coverage.clover

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "chat.freenode.net##add"
    on_success: change
    on_failure: always
